### ISSUE TITLE
java.lang.IllegalStateException: The configuration :runtimeClasspath was resolved from a thread not managed by Gradle.

### ISSUE THREAD

**Issue by ravitejrai** [rere252/jsp-angular-micro#1]
When Running Gradle appStart

I get the below error

Exception in thread "Thread-152" java.lang.IllegalStateException: The configuration :runtimeClasspath was resolved from a thread not managed by Gradle.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:588)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1900(DefaultConfiguration.java:149)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1328)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1318)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1390)

**Comment by rere252** [comment]
Should be resolved now. I also translated the Estonian parts of code into English and improved the README since I figured you are looking at this repo to learn about using Angular-based Web Components inside JSP-s.

**Comment by ravitejrai** [comment]
Thanks for the update that resolves it.
